export interface User {
  _id?: string

  name: string
  fullname: string
  degree: string

  login: string
  dateOfBirth: string | Date
  password: string

  avatarFileID?: string
  bannerFileID?: string

  city: string
  contact: {
    email?: string
    fb?: string
  }

  aboutme?: string
  icons?: string[]
  majors?: Major[]
  sciences?: Science[]
  researchInterests?: ResearchInterest[]

  students?: string[]

  isTutor: boolean
}

export interface Tutor {
  _id?: string

  name: string
  fullname: string
  degree: string

  city: string
  contact: {
    email?: string
    fb?: string
  }

  aboutme: string[]
  icons: string[]
  majors: Major[]
  sciences: Science[]
}

interface Major {
  name: string
  since: string
  university: string
  img: string
  spec?: string
}

interface Science {
  img: string
  name: string
}

export interface UserRegisterReq {
  name: string
  fullname: string
  login: string
  email: string
  // DateOfBirth: string
  password: string
}

export interface UserRegisterDummy {
  confirmedpassword: string
  rodo: boolean
}

export interface UserRegisterError {
  T: string
  ID: number
}

export interface UserLoginReq {
  login: string
  password: string
}

export interface ResearchInterest {
  science: string
  level: number
  img: string
  description?: string
}

export enum SciencesList {
  PHILOLOGY_IBERIAN = 'PHILOLOGY_IBERIAN', // PORTUGALY + SPAIN
  PHILOLOGY_ENGLISH = 'PHILOLOGY_ENGLISH',
  PHILOLOGY_FRANCE = 'PHILOLOGY_FRANCE', // AND BENELUX
  PHILOLOGY_ITALIAN = 'PHILOLOGY_ITALIAN',
  PHILOLOGY_GERMAN = 'PHILOLOGY_GERMAN', // DACHL
  PHILOLOGY_POLAND = 'PHILOLOGY_POLAND', // + UKRAINE + LITHUANIA
  PHILOLOGY_BALTIC = 'PHILOLOGY_BALTIC', // LATVIA + ESTONIA
  PHILOLOGY_NORDIC = 'PHILOLOGY_NORDIC', // SCANDINAVIA + FINLAND + ICELAND
  PHILOLOGY_RUSSIAN = 'PHILOLOGY_RUSSIAN',
  PHILOLOGY_CARPATHIAN = 'PHILOLOGY_CARPATHIAN', // HUNGARY + CZECHIA + SLOVAK REPUBLIC
  PHILOLOGY_ROMANIAN = 'PHILOLOGY_ROMANIAN', // + ROMANIA
  PHILOLOGY_BALKAN = 'PHILOLOGY_BALKAN', // YUGOSLAVIA + ALBANIA
  PHILOLOGY_GREEK = 'PHILOLOGY_GREEK',
  PHILOLOGY_TURKISH = 'PHILOLOGY_TURKISH',
  PHILOLOGY_AFRICAN = 'PHILOLOGY_AFRICAN',
  PHILOLOGY_HEBREW = 'PHILOLOGY_HEBREW',
  PHILOLOGY_MIDDLEEAST = 'PHILOLOGY_MIDDLEEAST', // MIDDLE EAST + ARABIAN + PERSIAN
  PHILOLOGY_INDIAN = 'PHILOLOGY_INDIAN',
  PHILOLOGY_ORIENTAL = 'PHILOLOGY_ORIENTAL',
  PHILOLOGY_CHINESE = 'PHILOLOGY_CHINESE',
  PHILOLOGY_KOREAN = 'PHILOLOGY_KOREAN',
  PHILOLOGY_JAPANESE = 'PHILOLOGY_JAPANESE',

  ANTHROPOLOGY = 'ANTHROPOLOGY',
  ARCHEOLOGY = 'ARCHEOLOGY',
  CULTURALSTUDIES = 'CULTURALSTUDIES',
  DEFENSESTUDIES = 'DEFENSESTUDIES',
  HISTORY = 'HISTORY',
  HISTORYOFART = 'HISTORYOFART',
  INTERNATIONALSTUDIES = 'INTERNATIONALSTUDIES',
  JOURNALISM = 'JOURNALISM',
  LAW = 'LAW',
  LINGUISTICS = 'LINGUISTICS',
  MEDIASTUDIES = 'CULTURALSTUDIES',
  POLITOLOGY = 'POLITOLOGY',
  PHILOSOPHY = 'PHILOSOPHY',
  PSYCHOLOGY = 'PSYCHOLOGY',
  RELIGIOUSSTUDIES = 'RELIGIOUSSTUDIES',
  SOCIOLOGY = 'SOCIOLOGY',

  ECONOMICS = 'ECONOMICS',
  FINANCES = 'FINANCES',
  ACCOUNTANCY = 'ACCOUNTANCY',
  ECONOMETRICS = 'ECONOMETRICS',
  GOVERNANCE = 'GOVERNANCE',
  MANAGEMENT = 'MANAGEMENT',

  ASTRONOMY = 'ASTRONOMY',
  BIOINFORMATICS = 'BIOINFORMATICS',
  BIOCHEMISTRY = 'BIOCHEMISTRY',
  BIOPHYSICS = 'BIOPHYSICS',
  BIOTECHNOLOGY = 'BIOTECHNOLOGY',
  BIOLOGY = 'BIOLOGY',
  CHEMISTRY = 'CHEMISTRY',
  PHYSICS = 'PHYSICS',
  GEOGRAPHY = 'GEOGRAPHY',
  GEOLOGY = 'GEOLOGY',
  INFORMATICS = 'INFORMATICS',
  MATHEMATICS = 'MATHEMATICS',
  ECOLOGY = 'ECOLOGY',

  BIOMEDICAL_ENGINEERING = 'BIOMEDICAL_ENGINEERING',
  CIVIL_ENGINEERING = 'CIVIL_ENGINEERING',
  ELECTRICAL_ENGINEERING = 'ELECTRICAL_ENGINEERING',
  ENVIRONMENTAL_ENGINEERING = 'ENVIRONMENTAL_ENGINEERING',
  MATERIALS_ENGINEERING = 'MATERIALS_ENGINEERING',
  QUANTUM_ENGINEERING = 'QUANTUM_ENGINEERING',
  ARCHITECTURE = 'ARCHITECTURE',
  COSMONAUTICS = 'COSMONAUTICS',
  ELECTRONICS = 'ELECTRONICS',
  ENERGETICS = 'ENERGETICS',
  MECHANICS = 'MECHANICS',
  MECHATRONICS = 'MECHATRONICS',
  METALURGY = 'METALURGY',
  NANOTECHNOLOGY = 'NANOTECHNOLOGY',
  ROBOTICS = 'ROBOTICS',
  TELECOMMUNICATIONS = 'TELECOMMUNICATIONS',
  TRANSPORT = 'TRANSPORT',
}

export enum ScienceLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
  MASTER = 'MASTER',
  VISIONARY = 'VISIONARY',
}
